Repository pre-onboarding-backend-F/1_SocialFeed_F, pull requests merged in 2023-10, with the labels that each got.

#33 Feat #20 게시글 조회 API
  src/commons/class/post.response.message.ts
  src/commons/enums/order-role.enum.ts
  src/commons/enums/search-role.enum.ts
  src/main.ts
  src/post/dto/query-post.dto.ts
  src/post/post.controller.ts
  src/post/post.service.ts
Labels: enhancement

#30 feat: 좋아요, 공유 API 및 Post 존재 여부 관심사 분리
  src/commons/class/post.response.message.ts
  src/commons/decorators/get.post.decorator.ts
  src/commons/guards/post.guard.ts
  src/post/post.controller.ts
  src/post/post.service.ts
Labels: enhancement

#41 fix: DB 시드 코드
  src/database/factories/posts.factory.ts
  src/database/factories/users.factory.ts
  src/database/seeds/main.seeder.ts
Labels: bug

#66 docs: README 작성
  README.md
Labels: documentation
